# Generated by Django 5.0.6 on 2024-06-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_registeredorg_org_admins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredorg',
            old_name='created_by',
            new_name='org_admin',
        ),
    ]
