# Generated by Django 5.0.6 on 2024-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_registeredorg_org_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('feedback_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user_feedback', models.TextField()),
                ('user_ratings', models.IntegerField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
