# Generated by Django 5.0.6 on 2024-07-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_userfeedback_organization_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='organization',
        ),
    ]
