# Generated by Django 5.0.6 on 2024-07-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_registeredorg_org_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.registeredorg'),
        ),
    ]
