# Generated by Django 5.0.6 on 2024-07-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_feedbacktype_alter_userfeedback_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
