# Generated by Django 5.0.6 on 2024-07-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_userfeedback_feedback_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackType',
        ),
    ]
