# Generated by Django 5.0.6 on 2024-07-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_delete_feedbacktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_types', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.feedbacktype'),
        ),
    ]
