# Generated by Django 5.0.6 on 2024-07-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_feedbacktype_alter_userfeedback_feedback_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacktype',
            old_name='f_types',
            new_name='name',
        ),
    ]
