# Generated by Django 5.0.6 on 2024-07-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_f_types_feedbacktype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredorg',
            name='org_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
