# Generated by Django 5.0.6 on 2024-08-09 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_registeredorg_org_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('org_address', models.TextField(blank=True, null=True)),
                ('org_description', models.TextField(blank=True, null=True)),
                ('org_descr', models.TextField(null=True)),
                ('org_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('org_website', models.URLField(blank=True, null=True)),
                ('org_facebook', models.URLField(blank=True, null=True)),
                ('org_twitter', models.URLField(blank=True, null=True)),
                ('org_instagram', models.URLField(blank=True, null=True)),
                ('org_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
