# Generated by Django 5.0.6 on 2024-08-09 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_orgprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='org_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.registeredorg'),
        ),
    ]
