# Generated by Django 5.0.6 on 2024-08-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_orgprofile_org_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgprofile',
            name='org_description',
        ),
    ]
