# Generated by Django 5.0.6 on 2024-09-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmissionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
