# Generated by Django 5.0.6 on 2024-09-26 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_formsubmissioncounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmissioncounter',
            name='organization',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submission_counter', to='base.registeredorg'),
            preserve_default=False,
        ),
    ]
