# Generated by Django 5.0.6 on 2024-09-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_formsubmissioncounter_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmissioncounter',
            name='organization',
        ),
    ]
