# Generated by Django 5.0.6 on 2024-10-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='no_of_notifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notification_status',
            field=models.TextField(blank=True, default='On', null=True),
        ),
    ]
