# Generated by Django 5.0.6 on 2024-10-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_notificationsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
