# Generated by Django 5.0.6 on 2024-10-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_notificationsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
