# Generated by Django 5.0.6 on 2024-10-08 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_delete_notificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_status', models.TextField(blank=True, default='On', null=True)),
                ('no_of_notifications', models.IntegerField(default=0)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.registeredorg')),
            ],
        ),
    ]
